/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package leasing.ViewLease;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import leasing.Controllers.AssetController;
import leasing.Controllers.BankAccountController;
import leasing.Controllers.CustomerController;
import leasing.Controllers.IncomeController;
import leasing.Controllers.LeaseController;
import leasing.Generators.ClientCodeGenerator;
import leasing.Generators.LeaseIDGenerator;
import leasing.Validation;
import leasing.models.Asset;
import leasing.models.Bank_Account;
import leasing.models.Customer;
import leasing.models.Income;
import leasing.models.Lease;

/**
 *
 * @author Sandali
 */
public class Customer_details extends javax.swing.JFrame {

    public static String LeaseId;
    public static String Clientcode;

    /**
     * Creates new form Customer_details
     */
    public Customer_details() {
        initComponents();
        try {
            String newClientcode = ClientCodeGenerator.getNewClientcode("Customer", "Clientcode", "C");
            clientcodeText.setText(newClientcode);
            Clientcode=clientcodeText.getText();

            String newLeaseID = LeaseIDGenerator.getnewLeaseID("Lease", "LeaseId", "L");
            leaseidText.setText(newLeaseID);
            LeaseId=leaseidText.getText();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Customer_details.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Customer_details.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        firstnameText = new javax.swing.JTextField();
        lastnameText = new javax.swing.JTextField();
        dobText = new javax.swing.JTextField();
        nicText = new javax.swing.JTextField();
        officetelText = new javax.swing.JTextField();
        hometelText = new javax.swing.JTextField();
        boText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        homeaddressText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        officeaddressText = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        customerButton = new javax.swing.JButton();
        jLabel91 = new javax.swing.JLabel();
        maleRadioButton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        jComboBox3 = new javax.swing.JComboBox();
        clientcodeText = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        leaseidText = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        incomepermonthText = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        sourceText = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        incomeidText = new javax.swing.JTextField();
        incomeButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        incomeTable = new javax.swing.JTable();
        jLabel35 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        yesRadioButton = new javax.swing.JRadioButton();
        noRadioButton = new javax.swing.JRadioButton();
        valueText = new javax.swing.JTextField();
        locationText = new javax.swing.JTextField();
        descriptionText = new javax.swing.JTextField();
        assetidText = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        assetButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        assetTable = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        accounttypeText = new javax.swing.JTextField();
        bankbranchText = new javax.swing.JTextField();
        banknameText = new javax.swing.JTextField();
        accountnoText = new javax.swing.JTextField();
        accountButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        bankaccountsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("Last Name :");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("N.I.C. No:");
        jPanel9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setText("Date of Birth :");
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setText("Office Tel:");
        jPanel9.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setText("Business/Occupation :");
        jPanel9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel19.setText("Residence Tel:");
        jPanel9.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel22.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel22.setText("Office Address :");
        jPanel9.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        jLabel23.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel23.setText("Home Address :");
        jPanel9.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        firstnameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameTextActionPerformed(evt);
            }
        });
        firstnameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                firstnameTextKeyReleased(evt);
            }
        });
        jPanel9.add(firstnameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 20, 190, -1));

        lastnameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameTextActionPerformed(evt);
            }
        });
        lastnameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lastnameTextKeyReleased(evt);
            }
        });
        jPanel9.add(lastnameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 228, -1));

        dobText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobTextActionPerformed(evt);
            }
        });
        dobText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dobTextKeyReleased(evt);
            }
        });
        jPanel9.add(dobText, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 228, -1));

        nicText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicTextActionPerformed(evt);
            }
        });
        nicText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nicTextKeyReleased(evt);
            }
        });
        jPanel9.add(nicText, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 228, -1));

        officetelText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                officetelTextActionPerformed(evt);
            }
        });
        officetelText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                officetelTextKeyReleased(evt);
            }
        });
        jPanel9.add(officetelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 310, -1));

        hometelText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hometelTextActionPerformed(evt);
            }
        });
        hometelText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                hometelTextKeyReleased(evt);
            }
        });
        jPanel9.add(hometelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 228, -1));

        boText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boTextActionPerformed(evt);
            }
        });
        boText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                boTextKeyReleased(evt);
            }
        });
        jPanel9.add(boText, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 310, -1));

        homeaddressText.setColumns(20);
        homeaddressText.setRows(5);
        homeaddressText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                homeaddressTextKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(homeaddressText);

        jPanel9.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 310, 40));

        officeaddressText.setColumns(20);
        officeaddressText.setRows(5);
        officeaddressText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                officeaddressTextKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(officeaddressText);

        jPanel9.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 310, 60));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setText("First Name :");
        jPanel9.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        customerButton.setBackground(new java.awt.Color(255, 255, 255));
        customerButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customerButton.setForeground(new java.awt.Color(51, 51, 51));
        customerButton.setText("Add");
        customerButton.setEnabled(false);
        customerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerButtonActionPerformed(evt);
            }
        });
        jPanel9.add(customerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 210, -1, -1));

        jLabel91.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel91.setText("Gender :");
        jPanel9.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        maleRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup4.add(maleRadioButton);
        maleRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        maleRadioButton.setText("Male");
        jPanel9.add(maleRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        femaleRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup4.add(femaleRadioButton);
        femaleRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        femaleRadioButton.setText("Female");
        jPanel9.add(femaleRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        jComboBox3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mr.", "Mrs.", "Miss" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel9.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 60, 20));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 930, 250));

        clientcodeText.setEditable(false);
        clientcodeText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        clientcodeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientcodeTextActionPerformed(evt);
            }
        });
        jPanel1.add(clientcodeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 210, -1));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Client Code");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 90, 20));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/leasing/images/next.jpg"))); // NOI18N
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 650, 60, 40));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("New Customer");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 150, 30));

        leaseidText.setEditable(false);
        leaseidText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        leaseidText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaseidTextActionPerformed(evt);
            }
        });
        jPanel3.add(leaseidText, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 210, 30));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        jLabel36.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Lease ID");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1000, 30));

        jPanel4.setBackground(new java.awt.Color(1, 162, 201));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(238, 238, 238));
        jLabel2.setText("Vehicle Leasing");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(787, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 30));

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(0, 153, 204));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel24.setText("Income per month :");
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        incomepermonthText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incomepermonthTextActionPerformed(evt);
            }
        });
        incomepermonthText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                incomepermonthTextKeyReleased(evt);
            }
        });
        jPanel7.add(incomepermonthText, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 130, 200, -1));

        jLabel21.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel21.setText("Rs.");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        sourceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceTextActionPerformed(evt);
            }
        });
        sourceText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sourceTextKeyReleased(evt);
            }
        });
        jPanel7.add(sourceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 228, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel20.setText("Income Id :");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 30, -1, -1));

        incomeidText.setEditable(false);
        jPanel7.add(incomeidText, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 228, -1));

        incomeButton.setBackground(new java.awt.Color(255, 255, 255));
        incomeButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        incomeButton.setForeground(new java.awt.Color(51, 51, 51));
        incomeButton.setText("Add");
        incomeButton.setEnabled(false);
        incomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incomeButtonActionPerformed(evt);
            }
        });
        jPanel7.add(incomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        incomeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Income ID", "Source", "Income per month"
            }
        ));
        jScrollPane3.setViewportView(incomeTable);

        jPanel7.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 490, 70));

        jLabel35.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel35.setText("Source :");
        jPanel7.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jTabbedPane1.addTab("Particulars of income", jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel27.setText("Rs.");
        jPanel8.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        jLabel26.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel26.setText("Description :");
        jPanel8.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel25.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel25.setText("Location :");
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 71, -1));

        jLabel28.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel28.setText("Value :");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel29.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel29.setText("Mortage :");
        jPanel8.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 30));

        yesRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(yesRadioButton);
        yesRadioButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        yesRadioButton.setText("Yes");
        jPanel8.add(yesRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        noRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(noRadioButton);
        noRadioButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        noRadioButton.setText("No");
        jPanel8.add(noRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, 22));

        valueText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valueTextKeyReleased(evt);
            }
        });
        jPanel8.add(valueText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 210, -1));

        locationText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationTextActionPerformed(evt);
            }
        });
        locationText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                locationTextKeyReleased(evt);
            }
        });
        jPanel8.add(locationText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 228, -1));

        descriptionText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionTextActionPerformed(evt);
            }
        });
        descriptionText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                descriptionTextKeyReleased(evt);
            }
        });
        jPanel8.add(descriptionText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 228, -1));

        assetidText.setEditable(false);
        jPanel8.add(assetidText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 228, -1));

        jLabel30.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel30.setText("Asset Id :");
        jPanel8.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        assetButton.setBackground(new java.awt.Color(255, 255, 255));
        assetButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        assetButton.setForeground(new java.awt.Color(51, 51, 51));
        assetButton.setText("Add");
        assetButton.setEnabled(false);
        assetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assetButtonActionPerformed(evt);
            }
        });
        jPanel8.add(assetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        assetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Asset ID", "Description", "Location", "Value", "Mortage"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(assetTable);

        jPanel8.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 530, 70));

        jTabbedPane1.addTab("Particulars of assets", jPanel8);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel31.setText("Account no.  :");
        jPanel10.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel32.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel32.setText("Name of bank :");
        jPanel10.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel33.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel33.setText("Name of branch :");
        jPanel10.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel34.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel34.setText("Type of account :");
        jPanel10.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        accounttypeText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                accounttypeTextKeyReleased(evt);
            }
        });
        jPanel10.add(accounttypeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 228, -1));

        bankbranchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankbranchTextActionPerformed(evt);
            }
        });
        bankbranchText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bankbranchTextKeyReleased(evt);
            }
        });
        jPanel10.add(bankbranchText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 228, -1));

        banknameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banknameTextActionPerformed(evt);
            }
        });
        banknameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                banknameTextKeyReleased(evt);
            }
        });
        jPanel10.add(banknameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 228, -1));

        accountnoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountnoTextActionPerformed(evt);
            }
        });
        accountnoText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                accountnoTextKeyReleased(evt);
            }
        });
        jPanel10.add(accountnoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 228, -1));

        accountButton.setBackground(new java.awt.Color(255, 255, 255));
        accountButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        accountButton.setForeground(new java.awt.Color(51, 51, 51));
        accountButton.setText("Add");
        accountButton.setEnabled(false);
        accountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountButtonActionPerformed(evt);
            }
        });
        jPanel10.add(accountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        bankaccountsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account no.", "Name of bank", "Name of branch", "Type of account"
            }
        ));
        jScrollPane5.setViewportView(bankaccountsTable);

        jPanel10.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, 80));

        jTabbedPane1.addTab("Particulars of accounts", jPanel10);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 270));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 930, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new Vehicle_details().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void customerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerButtonActionPerformed
        String Clientcode = clientcodeText.getText();
        String NIC = nicText.getText();
        String FirstName = firstnameText.getText();
        String LastName = lastnameText.getText();
        String DateofBirth = dobText.getText();
        String Tel_Home = hometelText.getText();
        String Tel_Office = officetelText.getText();
        String Address_Home = homeaddressText.getText();
        String Address_Office = officeaddressText.getText();
        String Bussiness_Occupation = boText.getText();
        String Gender = null;

        Customer customer = new Customer(Clientcode, NIC, FirstName, LastName, DateofBirth, Tel_Home, Tel_Office, Address_Home, Address_Office, Bussiness_Occupation, Gender);

        try {
            int res = CustomerController.addCustomer(customer);
            if (res > 0) {
                JOptionPane.showMessageDialog(this, "Customer Details are successfully added");
            } else {
                JOptionPane.showMessageDialog(this, "Added Failed");
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Customer_details.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Customer_details.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_customerButtonActionPerformed

    private void incomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incomeButtonActionPerformed
        String IncomeId = incomeidText.getText();
        String GuarantorId = null;
        String Clientcode = clientcodeText.getText();
        String Source = sourceText.getText();
        double Income_per_month = Double.parseDouble(incomepermonthText.getText());

        Income income = new Income(IncomeId, GuarantorId, Clientcode, Source, Income_per_month);
        try {
            int res = IncomeController.addIncome(income);
            if (res > 0) {
                JOptionPane.showMessageDialog(this, "Income details are added");
            } else {
                JOptionPane.showMessageDialog(this, "Added Failed");
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Customer_details.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Customer_details.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultTableModel tablem = (DefaultTableModel) incomeTable.getModel();
        Object[] row = {incomeidText.getText(), sourceText.getText(), incomepermonthText.getText()};
        tablem.addRow(row);

        incomeidText.setText("");
        sourceText.setText("");
        incomepermonthText.setText("");

    }//GEN-LAST:event_incomeButtonActionPerformed

    private void assetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assetButtonActionPerformed
        String AssetId = assetidText.getText();
        String GuarantorId = null;
        String Clientcode = clientcodeText.getText();
        String Description = descriptionText.getText();
        String Location = locationText.getText();
        double Valueofasset = Double.parseDouble(valueText.getText());
        String Mortage_if_;
        if (yesRadioButton.isSelected()) {
            Mortage_if_ = "Yes";
        } else {
            Mortage_if_ = "No";
        }

        Asset asset = new Asset(AssetId, GuarantorId, Clientcode, Description, Location, Valueofasset, Mortage_if_);
        try {
            int res = AssetController.addAsset(asset);
            if (res > 0) {
                JOptionPane.showMessageDialog(this, "Asset details are added");
            } else {
                JOptionPane.showMessageDialog(this, "Added Failed");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Customer_details.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Customer_details.class.getName()).log(Level.SEVERE, null, ex);
        }

        DefaultTableModel tablem = (DefaultTableModel) assetTable.getModel();
        Object[] row = {assetidText.getText(), descriptionText.getText(), locationText.getText(), valueText.getText(), Mortage_if_};
        tablem.addRow(row);

        assetidText.setText("");
        descriptionText.setText("");
        locationText.setText("");
        valueText.setText("");

    }//GEN-LAST:event_assetButtonActionPerformed

    private void accountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountButtonActionPerformed
        String Account_no = accountnoText.getText();
        String GuarantorId = null;
        String Clientcode = clientcodeText.getText();
        String NameofBank = banknameText.getText();
        String NameofBranch = bankbranchText.getText();
        String TypeofAccount = accounttypeText.getText();

        Bank_Account bankaccount = new Bank_Account(Account_no, GuarantorId, Clientcode, NameofBank, NameofBranch, TypeofAccount);
        try {
            int res = BankAccountController.addbankaccounts(bankaccount);
            if (res > 0) {
                JOptionPane.showMessageDialog(this, "Bank Account details are added");
            } else {
                JOptionPane.showMessageDialog(this, "Added Failed");
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Customer_details.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Customer_details.class.getName()).log(Level.SEVERE, null, ex);
        }

        DefaultTableModel tablem = (DefaultTableModel) bankaccountsTable.getModel();
        Object[] row = {accountnoText.getText(), banknameText.getText(), bankbranchText.getText(), accounttypeText.getText()};
        tablem.addRow(row);

        accountnoText.setText("");
        banknameText.setText("");
        bankbranchText.setText("");
        accounttypeText.setText("");
    }//GEN-LAST:event_accountButtonActionPerformed

    private void clientcodeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientcodeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientcodeTextActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void firstnameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameTextActionPerformed
        lastnameText.requestFocus();
    }//GEN-LAST:event_firstnameTextActionPerformed

    private void lastnameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameTextActionPerformed
        nicText.requestFocus();
    }//GEN-LAST:event_lastnameTextActionPerformed

    private void nicTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicTextActionPerformed
        dobText.requestFocus();
    }//GEN-LAST:event_nicTextActionPerformed

    private void dobTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobTextActionPerformed
        hometelText.requestFocus();
    }//GEN-LAST:event_dobTextActionPerformed

    private void hometelTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hometelTextActionPerformed
        homeaddressText.requestFocus();
    }//GEN-LAST:event_hometelTextActionPerformed

    private void officetelTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_officetelTextActionPerformed
        officeaddressText.requestFocus();
    }//GEN-LAST:event_officetelTextActionPerformed

    private void sourceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceTextActionPerformed
        incomepermonthText.requestFocus();
    }//GEN-LAST:event_sourceTextActionPerformed

    private void descriptionTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionTextActionPerformed
        locationText.requestFocus();
    }//GEN-LAST:event_descriptionTextActionPerformed

    private void locationTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationTextActionPerformed
        valueText.requestFocus();
    }//GEN-LAST:event_locationTextActionPerformed

    private void accountnoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountnoTextActionPerformed
        banknameText.requestFocus();
    }//GEN-LAST:event_accountnoTextActionPerformed

    private void banknameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banknameTextActionPerformed
        bankbranchText.requestFocus();
    }//GEN-LAST:event_banknameTextActionPerformed

    private void bankbranchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankbranchTextActionPerformed
        accounttypeText.requestFocus();
    }//GEN-LAST:event_bankbranchTextActionPerformed

    private void boTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boTextActionPerformed
        boolean b = false;
        if (maleRadioButton.isSelected() | femaleRadioButton.isSelected()) {
            b = true;
        }
        if (firstnameText.getText().equals("") | lastnameText.getText().equals("") | nicText.getText().equals("") | dobText.getText().equals("") | hometelText.getText().equals("") | homeaddressText.getText().equals("") | officetelText.getText().equals("") | officeaddressText.getText().equals("") | boText.getText().equals("") | b == false) {
            customerButton.setEnabled(true);
            customerButton.requestFocus(true);
        }
    }//GEN-LAST:event_boTextActionPerformed

    private void firstnameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstnameTextKeyReleased
        if (firstnameText.getText().equals("") == true) {
            customerButton.setEnabled(false);
        }
    }//GEN-LAST:event_firstnameTextKeyReleased

    private void lastnameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastnameTextKeyReleased
        if (lastnameText.getText().equals("") == true) {
            customerButton.setEnabled(false);
        }
    }//GEN-LAST:event_lastnameTextKeyReleased

    private void nicTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicTextKeyReleased
        if (nicText.getText().equals("") == true) {
            customerButton.setEnabled(false);
        }
        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            Validation.validateNIC(nicText);
        }
    }//GEN-LAST:event_nicTextKeyReleased

    private void dobTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dobTextKeyReleased
        if (dobText.getText().equals("") == true) {
            customerButton.setEnabled(false);
        }
    }//GEN-LAST:event_dobTextKeyReleased

    private void hometelTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hometelTextKeyReleased
        if (hometelText.getText().equals("") == true) {
            customerButton.setEnabled(false);
        }
    }//GEN-LAST:event_hometelTextKeyReleased

    private void homeaddressTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_homeaddressTextKeyReleased
        if (homeaddressText.getText().equals("") == true) {
            customerButton.setEnabled(false);
        }
    }//GEN-LAST:event_homeaddressTextKeyReleased

    private void officetelTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_officetelTextKeyReleased
        if (officetelText.getText().equals("") == true) {
            customerButton.setEnabled(false);
        }
    }//GEN-LAST:event_officetelTextKeyReleased

    private void officeaddressTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_officeaddressTextKeyReleased
        if (officeaddressText.getText().equals("") == true) {
            customerButton.setEnabled(false);
        }
    }//GEN-LAST:event_officeaddressTextKeyReleased

    private void boTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boTextKeyReleased
        if (boText.getText().equals("") == true) {
            customerButton.setEnabled(false);
        }
    }//GEN-LAST:event_boTextKeyReleased

    private void sourceTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sourceTextKeyReleased
        if (sourceText.getText().equals("") == true) {
            incomeButton.setEnabled(false);
        }
    }//GEN-LAST:event_sourceTextKeyReleased

    private void incomepermonthTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_incomepermonthTextKeyReleased
        if (incomepermonthText.getText().equals("") == true) {
            incomeButton.setEnabled(false);
        }
    }//GEN-LAST:event_incomepermonthTextKeyReleased

    private void descriptionTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descriptionTextKeyReleased
        if (descriptionText.getText().equals("") == true) {
            assetButton.setEnabled(false);
        }
    }//GEN-LAST:event_descriptionTextKeyReleased

    private void locationTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_locationTextKeyReleased
        if (locationText.getText().equals("") == true) {
            assetButton.setEnabled(false);
        }
    }//GEN-LAST:event_locationTextKeyReleased

    private void valueTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valueTextKeyReleased
        if (valueText.getText().equals("") == true) {
            assetButton.setEnabled(false);
        }
    }//GEN-LAST:event_valueTextKeyReleased

    private void accountnoTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accountnoTextKeyReleased
        if (accountnoText.getText().equals("") == true) {
            accountButton.setEnabled(false);
        }
    }//GEN-LAST:event_accountnoTextKeyReleased

    private void banknameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_banknameTextKeyReleased
        if (banknameText.getText().equals("") == true) {
            accountButton.setEnabled(false);
        }
    }//GEN-LAST:event_banknameTextKeyReleased

    private void bankbranchTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bankbranchTextKeyReleased
        if (bankbranchText.getText().equals("") == true) {
            accountButton.setEnabled(false);
        }
    }//GEN-LAST:event_bankbranchTextKeyReleased

    private void accounttypeTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accounttypeTextKeyReleased
        if (accounttypeText.getText().equals("") == true) {
            accountButton.setEnabled(false);
        }
    }//GEN-LAST:event_accounttypeTextKeyReleased

    private void incomepermonthTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incomepermonthTextActionPerformed
        if (sourceText.getText().equals("") | incomepermonthText.getText().equals("")) {
            customerButton.setEnabled(true);
            customerButton.requestFocus(true);
        }
    }//GEN-LAST:event_incomepermonthTextActionPerformed

    private void leaseidTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaseidTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leaseidTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_details().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountButton;
    private javax.swing.JTextField accountnoText;
    private javax.swing.JTextField accounttypeText;
    private javax.swing.JButton assetButton;
    private javax.swing.JTable assetTable;
    private javax.swing.JTextField assetidText;
    private javax.swing.JTable bankaccountsTable;
    private javax.swing.JTextField bankbranchText;
    private javax.swing.JTextField banknameText;
    private javax.swing.JTextField boText;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JTextField clientcodeText;
    private javax.swing.JButton customerButton;
    private javax.swing.JTextField descriptionText;
    private javax.swing.JTextField dobText;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JTextField firstnameText;
    private javax.swing.JTextArea homeaddressText;
    private javax.swing.JTextField hometelText;
    private javax.swing.JButton incomeButton;
    private javax.swing.JTable incomeTable;
    private javax.swing.JTextField incomeidText;
    private javax.swing.JTextField incomepermonthText;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lastnameText;
    private javax.swing.JTextField leaseidText;
    private javax.swing.JTextField locationText;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JTextField nicText;
    private javax.swing.JRadioButton noRadioButton;
    private javax.swing.JTextArea officeaddressText;
    private javax.swing.JTextField officetelText;
    private javax.swing.JTextField sourceText;
    private javax.swing.JTextField valueText;
    private javax.swing.JRadioButton yesRadioButton;
    // End of variables declaration//GEN-END:variables
}
