/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package leasing.ViewLease;

import com.sun.org.apache.xerces.internal.util.JAXPNamespaceContextWrapper;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import leasing.Controllers.InsuaranceController;
import leasing.Controllers.SupplierController;
import leasing.Controllers.VehicleController;
import leasing.Generators.ClientCodeGenerator;
import leasing.Generators.InsuaranceIDGenerator;
import leasing.Generators.SupplierIDGenerator;
import leasing.Generators.VehicleIDGenerator;
import leasing.models.Insuarance;
import leasing.models.Supplier;
import leasing.models.Vehicle;

/**
 *
 * @author Sandali
 */
public class Vehicle_details extends javax.swing.JFrame {
public static String VehicleId;
    /**
     * Creates new form Vehicle_details
     */
    public Vehicle_details() {
        initComponents();
        try {
            String newVehicleId = VehicleIDGenerator.getNewVehicleId("Vehicle", "VehicleId", "V");
            vehicleidText.setText(newVehicleId);
            
            String newSupplierId=SupplierIDGenerator.getNewSupplierId("Supplier","SupplierId","S");
            supplieridText.setText(newSupplierId);
            
            String newInsuaranceId=InsuaranceIDGenerator.getNewInsuaranceId("Insuarance","InsuaranceID","I");
            insuaranceidText.setText(newInsuaranceId);
            
            leaseidText.setText(Customer_details.LeaseId);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Vehicle_details.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Vehicle_details.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        makelText = new javax.swing.JTextField();
        valuationText = new javax.swing.JTextField();
        chasisText = new javax.swing.JTextField();
        sellingpriceText = new javax.swing.JTextField();
        enginenoText = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        vehicleButton = new javax.swing.JButton();
        brandnewCheckBox = new javax.swing.JCheckBox();
        registeredCheckBox = new javax.swing.JCheckBox();
        unregisteredCheckBox = new javax.swing.JCheckBox();
        reconditionCheckBox = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        yomText = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        regnoText = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        modelText = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        policynumText = new javax.swing.JTextField();
        insuarancetypeText = new javax.swing.JTextField();
        insuarancecompanyText = new javax.swing.JTextField();
        insuredamountText = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        insuaranceButton = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jTextField36 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        startdateText = new javax.swing.JTextField();
        jLabel81 = new javax.swing.JLabel();
        enddateText = new javax.swing.JTextField();
        jLabel82 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        supplieridText = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        vehicleidText = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        branchText = new javax.swing.JTextField();
        telnoText = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        supplierButton = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jTextField44 = new javax.swing.JTextField();
        jTextField45 = new javax.swing.JTextField();
        jTextField46 = new javax.swing.JTextField();
        jTextField47 = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jTextField48 = new javax.swing.JTextField();
        jTextField49 = new javax.swing.JTextField();
        jTextField50 = new javax.swing.JTextField();
        jTextField51 = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jTextField52 = new javax.swing.JTextField();
        jTextField53 = new javax.swing.JTextField();
        jTextField54 = new javax.swing.JTextField();
        jTextField55 = new javax.swing.JTextField();
        jLabel79 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressText = new javax.swing.JTextArea();
        jPanel10 = new javax.swing.JPanel();
        jLabel80 = new javax.swing.JLabel();
        insuaranceidText = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        leaseidText = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("Rs.");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("Selling Price :");
        jPanel9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setText("Chasis no.  :");
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel19.setText("Nature  :");
        jPanel9.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Vehicle Details");
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 150, -1));

        makelText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makelTextActionPerformed(evt);
            }
        });
        jPanel9.add(makelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 228, -1));

        valuationText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valuationTextActionPerformed(evt);
            }
        });
        jPanel9.add(valuationText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 200, -1));

        chasisText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chasisTextActionPerformed(evt);
            }
        });
        jPanel9.add(chasisText, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 240, -1));

        sellingpriceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellingpriceTextActionPerformed(evt);
            }
        });
        jPanel9.add(sellingpriceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 200, -1));
        jPanel9.add(enginenoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 240, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setText("Make:");
        jPanel9.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        vehicleButton.setBackground(new java.awt.Color(255, 255, 255));
        vehicleButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vehicleButton.setForeground(new java.awt.Color(0, 102, 153));
        vehicleButton.setText("Add");
        vehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleButtonActionPerformed(evt);
            }
        });
        jPanel9.add(vehicleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, -1, -1));

        brandnewCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(brandnewCheckBox);
        brandnewCheckBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        brandnewCheckBox.setText("Brand new");
        jPanel9.add(brandnewCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, -1, -1));

        registeredCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(registeredCheckBox);
        registeredCheckBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        registeredCheckBox.setText("Registered");
        jPanel9.add(registeredCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, -1, -1));

        unregisteredCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(unregisteredCheckBox);
        unregisteredCheckBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        unregisteredCheckBox.setText("Unregistered");
        jPanel9.add(unregisteredCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, -1, -1));

        reconditionCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(reconditionCheckBox);
        reconditionCheckBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        reconditionCheckBox.setText("Recondition");
        reconditionCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reconditionCheckBoxActionPerformed(evt);
            }
        });
        jPanel9.add(reconditionCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, -1, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel20.setText("Engine no. :");
        jPanel9.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setText("Valuation :");
        jPanel9.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        yomText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yomTextActionPerformed(evt);
            }
        });
        jPanel9.add(yomText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 190, -1));

        jLabel22.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel22.setText("Year of Manufacture   :");
        jPanel9.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel21.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel21.setText("Rs.");
        jPanel9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        jLabel23.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel23.setText("Register no. :");
        jPanel9.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        regnoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regnoTextActionPerformed(evt);
            }
        });
        jPanel9.add(regnoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 240, -1));

        jLabel24.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel24.setText("Model :");
        jPanel9.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        modelText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelTextActionPerformed(evt);
            }
        });
        jPanel9.add(modelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 228, -1));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 420, 530));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Vehicle ID");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 90, 20));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/leasing/images/next.jpg"))); // NOI18N
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 670, 60, 40));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel34.setText("Insuarance type :");
        jPanel13.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel35.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel35.setText("Insured amount :");
        jPanel13.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel36.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel36.setText("Insuarance Company  :");
        jPanel13.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel42.setText("Insuarance ");
        jPanel13.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 150, -1));

        policynumText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                policynumTextActionPerformed(evt);
            }
        });
        jPanel13.add(policynumText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 228, -1));

        insuarancetypeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuarancetypeTextActionPerformed(evt);
            }
        });
        jPanel13.add(insuarancetypeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 70, 230, -1));

        insuarancecompanyText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuarancecompanyTextActionPerformed(evt);
            }
        });
        jPanel13.add(insuarancecompanyText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 228, -1));

        insuredamountText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuredamountTextActionPerformed(evt);
            }
        });
        jPanel13.add(insuredamountText, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 100, 200, -1));

        jLabel43.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel43.setText("Policy no.  :");
        jPanel13.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        insuaranceButton.setBackground(new java.awt.Color(255, 255, 255));
        insuaranceButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        insuaranceButton.setForeground(new java.awt.Color(0, 102, 153));
        insuaranceButton.setText("Add");
        insuaranceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuaranceButtonActionPerformed(evt);
            }
        });
        jPanel13.add(insuaranceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel45.setText("Address :");
        jPanel14.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel46.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel46.setText("Tel.no :");
        jPanel14.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel47.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel47.setText("Branch :");
        jPanel14.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel48.setText("Vehicle Details");
        jPanel14.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 150, -1));
        jPanel14.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 228, -1));
        jPanel14.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 228, -1));
        jPanel14.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 228, -1));
        jPanel14.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 228, -1));

        jLabel49.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel49.setText(" Name :");
        jPanel14.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 132, 71));
        jButton7.setText("Add");
        jPanel14.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 420, 210));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel50.setText("Address :");
        jPanel15.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel51.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel51.setText("Tel.no :");
        jPanel15.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel52.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel52.setText("Branch :");
        jPanel15.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel53.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel53.setText("Vehicle Details");
        jPanel15.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 150, -1));
        jPanel15.add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 228, -1));
        jPanel15.add(jTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 228, -1));
        jPanel15.add(jTextField34, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 228, -1));
        jPanel15.add(jTextField35, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 228, -1));

        jLabel54.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel54.setText(" Name :");
        jPanel15.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 132, 71));
        jButton8.setText("Add");
        jPanel15.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel55.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel55.setText("Address :");
        jPanel16.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel56.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel56.setText("Tel.no :");
        jPanel16.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel57.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel57.setText("Branch :");
        jPanel16.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel58.setText("Vehicle Details");
        jPanel16.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 150, -1));
        jPanel16.add(jTextField36, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 228, -1));
        jPanel16.add(jTextField37, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 228, -1));
        jPanel16.add(jTextField38, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 228, -1));
        jPanel16.add(jTextField39, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 228, -1));

        jLabel59.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel59.setText(" Name :");
        jPanel16.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 132, 71));
        jButton9.setText("Add");
        jPanel16.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 420, 210));

        jPanel13.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 420, 210));

        startdateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startdateTextActionPerformed(evt);
            }
        });
        jPanel13.add(startdateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 228, -1));

        jLabel81.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel81.setText("Start date  :");
        jPanel13.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        jPanel13.add(enddateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 228, -1));

        jLabel82.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel82.setText("End date  :");
        jPanel13.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setText("Rs.");
        jPanel13.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 470, 260));

        supplieridText.setEditable(false);
        supplieridText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        supplieridText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(supplieridText, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 210, -1));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        jLabel44.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Supplier ID");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel44)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 90, -1));

        vehicleidText.setEditable(false);
        vehicleidText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vehicleidText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(vehicleidText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 210, -1));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel60.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel60.setText("Address :");
        jPanel17.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel61.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel61.setText("Tel.no :");
        jPanel17.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 50, 20));

        jLabel62.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel62.setText("Branch :");
        jPanel17.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel63.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel63.setText("Supplier Details");
        jPanel17.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 150, -1));

        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });
        jPanel17.add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 228, -1));
        jPanel17.add(branchText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 210, -1));

        telnoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telnoTextActionPerformed(evt);
            }
        });
        jPanel17.add(telnoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 228, -1));

        jLabel64.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel64.setText(" Name :");
        jPanel17.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        supplierButton.setBackground(new java.awt.Color(255, 255, 255));
        supplierButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        supplierButton.setForeground(new java.awt.Color(0, 102, 153));
        supplierButton.setText("Add");
        supplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierButtonActionPerformed(evt);
            }
        });
        jPanel17.add(supplierButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel65.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel65.setText("Address :");
        jPanel18.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel66.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel66.setText("Tel.no :");
        jPanel18.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel67.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel67.setText("Branch :");
        jPanel18.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel68.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel68.setText("Vehicle Details");
        jPanel18.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 150, -1));
        jPanel18.add(jTextField44, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 228, -1));
        jPanel18.add(jTextField45, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 228, -1));
        jPanel18.add(jTextField46, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 228, -1));
        jPanel18.add(jTextField47, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 228, -1));

        jLabel69.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel69.setText(" Name :");
        jPanel18.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(0, 132, 71));
        jButton11.setText("Add");
        jPanel18.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        jPanel17.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 420, 210));

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel70.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel70.setText("Address :");
        jPanel19.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel71.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel71.setText("Tel.no :");
        jPanel19.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel72.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel72.setText("Branch :");
        jPanel19.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel73.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel73.setText("Vehicle Details");
        jPanel19.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 150, -1));
        jPanel19.add(jTextField48, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 228, -1));
        jPanel19.add(jTextField49, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 228, -1));
        jPanel19.add(jTextField50, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 228, -1));
        jPanel19.add(jTextField51, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 228, -1));

        jLabel74.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel74.setText(" Name :");
        jPanel19.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jButton12.setBackground(new java.awt.Color(255, 255, 255));
        jButton12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton12.setForeground(new java.awt.Color(0, 132, 71));
        jButton12.setText("Add");
        jPanel19.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel75.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel75.setText("Address :");
        jPanel20.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel76.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel76.setText("Tel.no :");
        jPanel20.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel77.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel77.setText("Branch :");
        jPanel20.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel78.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel78.setText("Vehicle Details");
        jPanel20.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 150, -1));
        jPanel20.add(jTextField52, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 228, -1));
        jPanel20.add(jTextField53, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 228, -1));
        jPanel20.add(jTextField54, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 228, -1));
        jPanel20.add(jTextField55, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 228, -1));

        jLabel79.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel79.setText(" Name :");
        jPanel20.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jButton13.setBackground(new java.awt.Color(255, 255, 255));
        jButton13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton13.setForeground(new java.awt.Color(0, 132, 71));
        jButton13.setText("Add");
        jPanel20.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        jPanel19.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 420, 210));

        jPanel17.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 420, 210));

        addressText.setColumns(20);
        addressText.setRows(5);
        jScrollPane1.setViewportView(addressText);

        jPanel17.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 230, 40));

        jPanel1.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 470, 210));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));

        jLabel80.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(255, 255, 255));
        jLabel80.setText("Insuarance  ID");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel80)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, -1, -1));

        insuaranceidText.setEditable(false);
        insuaranceidText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        insuaranceidText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(insuaranceidText, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 210, -1));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vehicle Details");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 113, 30));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        jLabel25.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Lease ID");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, 20));

        leaseidText.setEditable(false);
        leaseidText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        leaseidText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(leaseidText, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 210, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1000, 30));

        jPanel4.setBackground(new java.awt.Color(1, 162, 201));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(238, 238, 238));
        jLabel2.setText("Vehicle Leasing");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(796, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1000, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/leasing/images/back.jpg"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 670, -1, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("View");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 90, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reconditionCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reconditionCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reconditionCheckBoxActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new Guarantor_details().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Customer_details().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void vehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleButtonActionPerformed
        String VehicleId = vehicleidText.getText();
        String SupplierId = supplieridText.getText();
        String InsuaranceID = insuaranceidText.getText();
        String Make = makelText.getText();
        String Model = modelText.getText();
        double Valuation = Double.parseDouble(valuationText.getText());
        double SellingPrice = Double.parseDouble(sellingpriceText.getText());
        String Manufactureyear = yomText.getText();
        String Chasis_no = chasisText.getText();
        String RegNo = regnoText.getText();
        String Engine_no = enginenoText.getText();
        String Nature = null;
        
        VehicleId=vehicleidText.getText();

        if (brandnewCheckBox.isSelected()) {
            Nature = "Brand New";
        } else if (reconditionCheckBox.isSelected()) {
            Nature = "Recondition";
        } else if (unregisteredCheckBox.isSelected()) {
            Nature = "Unregistered";
        } else if (registeredCheckBox.isSelected()) {
            Nature = "Registered";
        }

        Vehicle vehicle = new Vehicle(VehicleId, SupplierId, InsuaranceID, Make, Model, Valuation, SellingPrice, Manufactureyear, Chasis_no, RegNo, Engine_no, Nature);
        try {
            int res = VehicleController.addVehicle(vehicle);
            if (res > 0) {
                JOptionPane.showMessageDialog(this, "Vehicle Details are successfully added");
            } else {
                JOptionPane.showMessageDialog(this, "Added failed");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Vehicle_details.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Vehicle_details.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_vehicleButtonActionPerformed

    private void supplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierButtonActionPerformed
        String SupplierId = supplieridText.getText();
        String Name = nameText.getText();
        String Address = addressText.getText();
        String Branch = branchText.getText();
        String Tel_no = telnoText.getText();

        Supplier supplier = new Supplier(SupplierId, Name, Address, Branch, Tel_no);
        try {
            int res = SupplierController.addSupplier(supplier);
            if (res > 0) {
                JOptionPane.showMessageDialog(this, "Supplier Details are successfully added");
            } else {
                JOptionPane.showMessageDialog(this, "Added failed");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Vehicle_details.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Vehicle_details.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_supplierButtonActionPerformed

    private void insuaranceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuaranceButtonActionPerformed
        String InsuaranceID = insuaranceidText.getText();
        String Policy_no = policynumText.getText();
        String Insuarance_company = insuarancecompanyText.getText();
        double InsuredAmount = Double.parseDouble(insuredamountText.getText());
        String Insuarance_type = insuarancetypeText.getText();
        String Start_Date = startdateText.getText();
        String End_Date = enddateText.getText();

        Insuarance insuarance = new Insuarance(InsuaranceID, Policy_no, Insuarance_company, InsuredAmount, Insuarance_type, Start_Date, End_Date);
        try {
            int res = InsuaranceController.addInsuarance(insuarance);
            if (res > 0) {
                JOptionPane.showMessageDialog(this, "Insuarance Details are successfully added");
            } else {
                JOptionPane.showMessageDialog(this, "Added failed");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Vehicle_details.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Vehicle_details.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_insuaranceButtonActionPerformed

    private void makelTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makelTextActionPerformed
        modelText.requestFocus();
    }//GEN-LAST:event_makelTextActionPerformed

    private void modelTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelTextActionPerformed
        valuationText.requestFocus();
    }//GEN-LAST:event_modelTextActionPerformed

    private void valuationTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valuationTextActionPerformed
        sellingpriceText.requestFocus();
    }//GEN-LAST:event_valuationTextActionPerformed

    private void sellingpriceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellingpriceTextActionPerformed
        yomText.requestFocus();
    }//GEN-LAST:event_sellingpriceTextActionPerformed

    private void yomTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yomTextActionPerformed
        chasisText.requestFocus();
    }//GEN-LAST:event_yomTextActionPerformed

    private void chasisTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chasisTextActionPerformed
        regnoText.requestFocus();
    }//GEN-LAST:event_chasisTextActionPerformed

    private void regnoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regnoTextActionPerformed
        enginenoText.requestFocus();
    }//GEN-LAST:event_regnoTextActionPerformed

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        addressText.requestFocus();
    }//GEN-LAST:event_nameTextActionPerformed

    private void telnoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telnoTextActionPerformed
        telnoText.requestFocus();
    }//GEN-LAST:event_telnoTextActionPerformed

    private void policynumTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_policynumTextActionPerformed
        insuarancecompanyText.requestFocus();
    }//GEN-LAST:event_policynumTextActionPerformed

    private void insuarancetypeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuarancetypeTextActionPerformed
        insuredamountText.requestFocus();
    }//GEN-LAST:event_insuarancetypeTextActionPerformed

    private void insuredamountTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuredamountTextActionPerformed
        insuarancetypeText.requestFocus();
    }//GEN-LAST:event_insuredamountTextActionPerformed

    private void insuarancecompanyTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuarancecompanyTextActionPerformed
        startdateText.requestFocus();
    }//GEN-LAST:event_insuarancecompanyTextActionPerformed

    private void startdateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startdateTextActionPerformed
        enddateText.requestFocus();
    }//GEN-LAST:event_startdateTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vehicle_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vehicle_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vehicle_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vehicle_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vehicle_details().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addressText;
    private javax.swing.JTextField branchText;
    private javax.swing.JCheckBox brandnewCheckBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField chasisText;
    private javax.swing.JTextField enddateText;
    private javax.swing.JTextField enginenoText;
    private javax.swing.JButton insuaranceButton;
    private javax.swing.JTextField insuarancecompanyText;
    private javax.swing.JTextField insuaranceidText;
    private javax.swing.JTextField insuarancetypeText;
    private javax.swing.JTextField insuredamountText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField48;
    private javax.swing.JTextField jTextField49;
    private javax.swing.JTextField jTextField50;
    private javax.swing.JTextField jTextField51;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField jTextField53;
    private javax.swing.JTextField jTextField54;
    private javax.swing.JTextField jTextField55;
    private javax.swing.JTextField leaseidText;
    private javax.swing.JTextField makelText;
    private javax.swing.JTextField modelText;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField policynumText;
    private javax.swing.JCheckBox reconditionCheckBox;
    private javax.swing.JCheckBox registeredCheckBox;
    private javax.swing.JTextField regnoText;
    private javax.swing.JTextField sellingpriceText;
    private javax.swing.JTextField startdateText;
    private javax.swing.JButton supplierButton;
    private javax.swing.JTextField supplieridText;
    private javax.swing.JTextField telnoText;
    private javax.swing.JCheckBox unregisteredCheckBox;
    private javax.swing.JTextField valuationText;
    private javax.swing.JButton vehicleButton;
    private javax.swing.JTextField vehicleidText;
    private javax.swing.JTextField yomText;
    // End of variables declaration//GEN-END:variables
}
